// ISO 3166-1 Country codes and names with regions
export const countriesData = [
  { code: 'AF', name: 'Afghanistan', region: 'Asia' },
  { code: 'AL', name: 'Albania', region: 'Europe' },
  { code: 'DZ', name: 'Algeria', region: 'Africa' },
  { code: 'AS', name: 'American Samoa', region: 'Oceania' },
  { code: 'AD', name: 'Andorra', region: 'Europe' },
  { code: 'AO', name: 'Angola', region: 'Africa' },
  { code: 'AI', name: 'Anguilla', region: 'North America' },
  { code: 'AQ', name: 'Antarctica', region: 'Antarctica' },
  { code: 'AG', name: 'Antigua and Barbuda', region: 'North America' },
  { code: 'AR', name: 'Argentina', region: 'South America' },
  { code: 'AM', name: 'Armenia', region: 'Asia' },
  { code: 'AW', name: 'Aruba', region: 'North America' },
  { code: 'AU', name: 'Australia', region: 'Oceania' },
  { code: 'AT', name: 'Austria', region: 'Europe' },
  { code: 'AZ', name: 'Azerbaijan', region: 'Asia' },
  { code: 'BS', name: 'Bahamas', region: 'North America' },
  { code: 'BH', name: 'Bahrain', region: 'Asia' },
  { code: 'BD', name: 'Bangladesh', region: 'Asia' },
  { code: 'BB', name: 'Barbados', region: 'North America' },
  { code: 'BY', name: 'Belarus', region: 'Europe' },
  { code: 'BE', name: 'Belgium', region: 'Europe' },
  { code: 'BZ', name: 'Belize', region: 'North America' },
  { code: 'BJ', name: 'Benin', region: 'Africa' },
  { code: 'BM', name: 'Bermuda', region: 'North America' },
  { code: 'BT', name: 'Bhutan', region: 'Asia' },
  { code: 'BO', name: 'Bolivia', region: 'South America' },
  { code: 'BA', name: 'Bosnia and Herzegovina', region: 'Europe' },
  { code: 'BW', name: 'Botswana', region: 'Africa' },
  { code: 'BV', name: 'Bouvet Island', region: 'Antarctica' },
  { code: 'BR', name: 'Brazil', region: 'South America' },
  { code: 'IO', name: 'British Indian Ocean Territory', region: 'Asia' },
  { code: 'BN', name: 'Brunei', region: 'Asia' },
  { code: 'BG', name: 'Bulgaria', region: 'Europe' },
  { code: 'BF', name: 'Burkina Faso', region: 'Africa' },
  { code: 'BI', name: 'Burundi', region: 'Africa' },
  { code: 'KH', name: 'Cambodia', region: 'Asia' },
  { code: 'CM', name: 'Cameroon', region: 'Africa' },
  { code: 'CA', name: 'Canada', region: 'North America' },
  { code: 'CV', name: 'Cape Verde', region: 'Africa' },
  { code: 'KY', name: 'Cayman Islands', region: 'North America' },
  { code: 'CF', name: 'Central African Republic', region: 'Africa' },
  { code: 'TD', name: 'Chad', region: 'Africa' },
  { code: 'CL', name: 'Chile', region: 'South America' },
  { code: 'CN', name: 'China', region: 'Asia' },
  { code: 'CX', name: 'Christmas Island', region: 'Asia' },
  { code: 'CC', name: 'Cocos Islands', region: 'Asia' },
  { code: 'CO', name: 'Colombia', region: 'South America' },
  { code: 'KM', name: 'Comoros', region: 'Africa' },
  { code: 'CG', name: 'Congo', region: 'Africa' },
  { code: 'CD', name: 'Congo (Democratic Republic)', region: 'Africa' },
  { code: 'CK', name: 'Cook Islands', region: 'Oceania' },
  { code: 'CR', name: 'Costa Rica', region: 'North America' },
  { code: 'CI', name: 'Côte d\'Ivoire', region: 'Africa' },
  { code: 'HR', name: 'Croatia', region: 'Europe' },
  { code: 'CU', name: 'Cuba', region: 'North America' },
  { code: 'CY', name: 'Cyprus', region: 'Europe' },
  { code: 'CZ', name: 'Czech Republic', region: 'Europe' },
  { code: 'DK', name: 'Denmark', region: 'Europe' },
  { code: 'DJ', name: 'Djibouti', region: 'Africa' },
  { code: 'DM', name: 'Dominica', region: 'North America' },
  { code: 'DO', name: 'Dominican Republic', region: 'North America' },
  { code: 'EC', name: 'Ecuador', region: 'South America' },
  { code: 'EG', name: 'Egypt', region: 'Africa' },
  { code: 'SV', name: 'El Salvador', region: 'North America' },
  { code: 'GQ', name: 'Equatorial Guinea', region: 'Africa' },
  { code: 'ER', name: 'Eritrea', region: 'Africa' },
  { code: 'EE', name: 'Estonia', region: 'Europe' },
  { code: 'ET', name: 'Ethiopia', region: 'Africa' },
  { code: 'FK', name: 'Falkland Islands', region: 'South America' },
  { code: 'FO', name: 'Faroe Islands', region: 'Europe' },
  { code: 'FJ', name: 'Fiji', region: 'Oceania' },
  { code: 'FI', name: 'Finland', region: 'Europe' },
  { code: 'FR', name: 'France', region: 'Europe' },
  { code: 'GF', name: 'French Guiana', region: 'South America' },
  { code: 'PF', name: 'French Polynesia', region: 'Oceania' },
  { code: 'TF', name: 'French Southern Territories', region: 'Antarctica' },
  { code: 'GA', name: 'Gabon', region: 'Africa' },
  { code: 'GM', name: 'Gambia', region: 'Africa' },
  { code: 'GE', name: 'Georgia', region: 'Asia' },
  { code: 'DE', name: 'Germany', region: 'Europe' },
  { code: 'GH', name: 'Ghana', region: 'Africa' },
  { code: 'GI', name: 'Gibraltar', region: 'Europe' },
  { code: 'GR', name: 'Greece', region: 'Europe' },
  { code: 'GL', name: 'Greenland', region: 'North America' },
  { code: 'GD', name: 'Grenada', region: 'North America' },
  { code: 'GP', name: 'Guadeloupe', region: 'North America' },
  { code: 'GU', name: 'Guam', region: 'Oceania' },
  { code: 'GT', name: 'Guatemala', region: 'North America' },
  { code: 'GG', name: 'Guernsey', region: 'Europe' },
  { code: 'GN', name: 'Guinea', region: 'Africa' },
  { code: 'GW', name: 'Guinea-Bissau', region: 'Africa' },
  { code: 'GY', name: 'Guyana', region: 'South America' },
  { code: 'HT', name: 'Haiti', region: 'North America' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', region: 'Antarctica' },
  { code: 'VA', name: 'Holy See', region: 'Europe' },
  { code: 'HN', name: 'Honduras', region: 'North America' },
  { code: 'HK', name: 'Hong Kong', region: 'Asia' },
  { code: 'HU', name: 'Hungary', region: 'Europe' },
  { code: 'IS', name: 'Iceland', region: 'Europe' },
  { code: 'IN', name: 'India', region: 'Asia' },
  { code: 'ID', name: 'Indonesia', region: 'Asia' },
  { code: 'IR', name: 'Iran', region: 'Asia' },
  { code: 'IQ', name: 'Iraq', region: 'Asia' },
  { code: 'IE', name: 'Ireland', region: 'Europe' },
  { code: 'IM', name: 'Isle of Man', region: 'Europe' },
  { code: 'IL', name: 'Israel', region: 'Asia' },
  { code: 'IT', name: 'Italy', region: 'Europe' },
  { code: 'JM', name: 'Jamaica', region: 'North America' },
  { code: 'JP', name: 'Japan', region: 'Asia' },
  { code: 'JE', name: 'Jersey', region: 'Europe' },
  { code: 'JO', name: 'Jordan', region: 'Asia' },
  { code: 'KZ', name: 'Kazakhstan', region: 'Asia' },
  { code: 'KE', name: 'Kenya', region: 'Africa' },
  { code: 'KI', name: 'Kiribati', region: 'Oceania' },
  { code: 'KP', name: 'Korea (North)', region: 'Asia' },
  { code: 'KR', name: 'Korea (South)', region: 'Asia' },
  { code: 'KW', name: 'Kuwait', region: 'Asia' },
  { code: 'KG', name: 'Kyrgyzstan', region: 'Asia' },
  { code: 'LA', name: 'Laos', region: 'Asia' },
  { code: 'LV', name: 'Latvia', region: 'Europe' },
  { code: 'LB', name: 'Lebanon', region: 'Asia' },
  { code: 'LS', name: 'Lesotho', region: 'Africa' },
  { code: 'LR', name: 'Liberia', region: 'Africa' },
  { code: 'LY', name: 'Libya', region: 'Africa' },
  { code: 'LI', name: 'Liechtenstein', region: 'Europe' },
  { code: 'LT', name: 'Lithuania', region: 'Europe' },
  { code: 'LU', name: 'Luxembourg', region: 'Europe' },
  { code: 'MO', name: 'Macao', region: 'Asia' },
  { code: 'MK', name: 'Macedonia', region: 'Europe' },
  { code: 'MG', name: 'Madagascar', region: 'Africa' },
  { code: 'MW', name: 'Malawi', region: 'Africa' },
  { code: 'MY', name: 'Malaysia', region: 'Asia' },
  { code: 'MV', name: 'Maldives', region: 'Asia' },
  { code: 'ML', name: 'Mali', region: 'Africa' },
  { code: 'MT', name: 'Malta', region: 'Europe' },
  { code: 'MH', name: 'Marshall Islands', region: 'Oceania' },
  { code: 'MQ', name: 'Martinique', region: 'North America' },
  { code: 'MR', name: 'Mauritania', region: 'Africa' },
  { code: 'MU', name: 'Mauritius', region: 'Africa' },
  { code: 'YT', name: 'Mayotte', region: 'Africa' },
  { code: 'MX', name: 'Mexico', region: 'North America' },
  { code: 'FM', name: 'Micronesia', region: 'Oceania' },
  { code: 'MD', name: 'Moldova', region: 'Europe' },
  { code: 'MC', name: 'Monaco', region: 'Europe' },
  { code: 'MN', name: 'Mongolia', region: 'Asia' },
  { code: 'ME', name: 'Montenegro', region: 'Europe' },
  { code: 'MA', name: 'Morocco', region: 'Africa' },
  { code: 'MZ', name: 'Mozambique', region: 'Africa' },
  { code: 'MM', name: 'Myanmar', region: 'Asia' },
  { code: 'NA', name: 'Namibia', region: 'Africa' },
  { code: 'NR', name: 'Nauru', region: 'Oceania' },
  { code: 'NP', name: 'Nepal', region: 'Asia' },
  { code: 'NL', name: 'Netherlands', region: 'Europe' },
  { code: 'AN', name: 'Netherlands Antilles', region: 'North America' },
  { code: 'NC', name: 'New Caledonia', region: 'Oceania' },
  { code: 'NZ', name: 'New Zealand', region: 'Oceania' },
  { code: 'NI', name: 'Nicaragua', region: 'North America' },
  { code: 'NE', name: 'Niger', region: 'Africa' },
  { code: 'NG', name: 'Nigeria', region: 'Africa' },
  { code: 'NU', name: 'Niue', region: 'Oceania' },
  { code: 'NF', name: 'Norfolk Island', region: 'Oceania' },
  { code: 'MP', name: 'Northern Mariana Islands', region: 'Oceania' },
  { code: 'NO', name: 'Norway', region: 'Europe' },
  { code: 'OM', name: 'Oman', region: 'Asia' },
  { code: 'PK', name: 'Pakistan', region: 'Asia' },
  { code: 'PW', name: 'Palau', region: 'Oceania' },
  { code: 'PS', name: 'Palestine', region: 'Asia' },
  { code: 'PA', name: 'Panama', region: 'North America' },
  { code: 'PG', name: 'Papua New Guinea', region: 'Oceania' },
  { code: 'PY', name: 'Paraguay', region: 'South America' },
  { code: 'PE', name: 'Peru', region: 'South America' },
  { code: 'PH', name: 'Philippines', region: 'Asia' },
  { code: 'PN', name: 'Pitcairn Islands', region: 'Oceania' },
  { code: 'PL', name: 'Poland', region: 'Europe' },
  { code: 'PT', name: 'Portugal', region: 'Europe' },
  { code: 'PR', name: 'Puerto Rico', region: 'North America' },
  { code: 'QA', name: 'Qatar', region: 'Asia' },
  { code: 'RE', name: 'Réunion', region: 'Africa' },
  { code: 'RO', name: 'Romania', region: 'Europe' },
  { code: 'RU', name: 'Russia', region: 'Europe' },
  { code: 'RW', name: 'Rwanda', region: 'Africa' },
  { code: 'BL', name: 'Saint Barthélemy', region: 'North America' },
  { code: 'SH', name: 'Saint Helena', region: 'Africa' },
  { code: 'KN', name: 'Saint Kitts and Nevis', region: 'North America' },
  { code: 'LC', name: 'Saint Lucia', region: 'North America' },
  { code: 'MF', name: 'Saint Martin', region: 'North America' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', region: 'North America' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', region: 'North America' },
  { code: 'WS', name: 'Samoa', region: 'Oceania' },
  { code: 'SM', name: 'San Marino', region: 'Europe' },
  { code: 'ST', name: 'São Tomé and Príncipe', region: 'Africa' },
  { code: 'SA', name: 'Saudi Arabia', region: 'Asia' },
  { code: 'SN', name: 'Senegal', region: 'Africa' },
  { code: 'RS', name: 'Serbia', region: 'Europe' },
  { code: 'SC', name: 'Seychelles', region: 'Africa' },
  { code: 'SL', name: 'Sierra Leone', region: 'Africa' },
  { code: 'SG', name: 'Singapore', region: 'Asia' },
  { code: 'SK', name: 'Slovakia', region: 'Europe' },
  { code: 'SI', name: 'Slovenia', region: 'Europe' },
  { code: 'SB', name: 'Solomon Islands', region: 'Oceania' },
  { code: 'SO', name: 'Somalia', region: 'Africa' },
  { code: 'ZA', name: 'South Africa', region: 'Africa' },
  { code: 'SS', name: 'South Sudan', region: 'Africa' },
  { code: 'ES', name: 'Spain', region: 'Europe' },
  { code: 'LK', name: 'Sri Lanka', region: 'Asia' },
  { code: 'SD', name: 'Sudan', region: 'Africa' },
  { code: 'SR', name: 'Suriname', region: 'South America' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', region: 'Europe' },
  { code: 'SZ', name: 'Swaziland', region: 'Africa' },
  { code: 'SE', name: 'Sweden', region: 'Europe' },
  { code: 'CH', name: 'Switzerland', region: 'Europe' },
  { code: 'SY', name: 'Syria', region: 'Asia' },
  { code: 'TW', name: 'Taiwan', region: 'Asia' },
  { code: 'TJ', name: 'Tajikistan', region: 'Asia' },
  { code: 'TZ', name: 'Tanzania', region: 'Africa' },
  { code: 'TH', name: 'Thailand', region: 'Asia' },
  { code: 'TL', name: 'Timor-Leste', region: 'Asia' },
  { code: 'TG', name: 'Togo', region: 'Africa' },
  { code: 'TK', name: 'Tokelau', region: 'Oceania' },
  { code: 'TO', name: 'Tonga', region: 'Oceania' },
  { code: 'TT', name: 'Trinidad and Tobago', region: 'North America' },
  { code: 'TN', name: 'Tunisia', region: 'Africa' },
  { code: 'TR', name: 'Turkey', region: 'Asia' },
  { code: 'TM', name: 'Turkmenistan', region: 'Asia' },
  { code: 'TC', name: 'Turks and Caicos Islands', region: 'North America' },
  { code: 'TV', name: 'Tuvalu', region: 'Oceania' },
  { code: 'UG', name: 'Uganda', region: 'Africa' },
  { code: 'UA', name: 'Ukraine', region: 'Europe' },
  { code: 'AE', name: 'United Arab Emirates', region: 'Asia' },
  { code: 'GB', name: 'United Kingdom', region: 'Europe' },
  { code: 'US', name: 'United States', region: 'North America' },
  { code: 'UM', name: 'United States Minor Outlying Islands', region: 'Oceania' },
  { code: 'UY', name: 'Uruguay', region: 'South America' },
  { code: 'UZ', name: 'Uzbekistan', region: 'Asia' },
  { code: 'VU', name: 'Vanuatu', region: 'Oceania' },
  { code: 'VE', name: 'Venezuela', region: 'South America' },
  { code: 'VN', name: 'Vietnam', region: 'Asia' },
  { code: 'VG', name: 'Virgin Islands (British)', region: 'North America' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', region: 'North America' },
  { code: 'WF', name: 'Wallis and Futuna', region: 'Oceania' },
  { code: 'EH', name: 'Western Sahara', region: 'Africa' },
  { code: 'YE', name: 'Yemen', region: 'Asia' },
  { code: 'ZM', name: 'Zambia', region: 'Africa' },
  { code: 'ZW', name: 'Zimbabwe', region: 'Africa' },
];
